name: Deploy Next.js to cPanel

on:
  push:
    branches:
      - master # Matches your master branch

jobs:
  web-deploy:
    name: Build and Transfer
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn' # Automatically caches your yarn dependencies for faster builds

    - name: Install dependencies
      run: yarn install --frozen-lockfile # This is the Yarn equivalent of 'npm ci'

    - name: Run Next.js Build
      run: yarn build
      env:
        NEXT_PRIVATE_LOCAL_WEBPACK: 'true'

    - name: Sync files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /home/conswwpe/constrally
        dangerous-clean-html: false
